// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  bookSidebar: [
    {
      type: 'category',
      label: 'Module 1: Introduction',
      items: [{type: 'autogenerated', dirName: '01-intro'}],
    },
    {
      type: 'category',
      label: 'Module 2: Core Technologies',
      items: [
          {type: 'autogenerated', dirName: '02-ros2'},
          {type: 'autogenerated', dirName: '03-simulation'},
      ],
    },
    {
      type: 'category',
      label: 'Module 3: Advanced AI & Robotics',
      items: [
          {type: 'autogenerated', dirName: '04-isaac'},
          {type: 'autogenerated', dirName: '05-vla'},
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Application & Project',
      items: [
          {type: 'autogenerated', dirName: 'hardware-guide'},
          {type: 'autogenerated', dirName: 'capstone'},
      ],
    },
  ],
};

export default sidebars;
